apiVersion: v1
kind: Service
metadata:
  name: aristotle-api
  namespace: aristotle-api-staging

spec:
  ports:
    - protocol: TCP
      name: web
      port: 5000
  selector:
    app: aristotle-api